theme: jekyll-theme-cayman
title: Antoine Vaucamps - Portfolio
author: Antoine Vaucamps
email: antoine.vaucamps@gmail.com
description: Antoine Vaucamps - AI, Machine Learning, Software Engineering
url: "https://avaucamps.github.io"
github_username: avaucamps
